# Generated by Django 4.2.5 on 2023-10-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_category_alter_comment_commentor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing_id',
        ),
    ]
